apiVersion: v1
kind: Service
metadata:
  name: postgresql-service           
spec:
  type: ClusterIP                    
  selector:
    app: postgresql
  ports:
  - name: pg
    port: 5432                     
    targetPort: 5432                 